#! /bin/bash

rm -rf target/classes && mkdir -p target/classes
CP=`lein classpath`
find src/java -name "*.java" | xargs javac -Xlint:unchecked -encoding utf8 -cp $CP -d target/classes -sourcepath src/java/
